using WebAppPortalApi.Database.Tables.dbo;

namespace WebAppPortalApi.Database.Extensions
{
    internal static class SeederExtensions
    {

        public static void Seed(this DBContext context)
        {
            if (!context.Users.Any() && !context.Products.Any())
            {
                context.Users.AddRange(
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe1", EmailAddress = "john.doe1@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe2", EmailAddress = "john.doe2@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe3", EmailAddress = "john.doe3@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe4", EmailAddress = "john.doe4@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe5", EmailAddress = "john.doe5@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe6", EmailAddress = "john.doe6@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe7", EmailAddress = "john.doe7@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe8", EmailAddress = "john.doe8@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe9", EmailAddress = "john.doe9@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe10", EmailAddress = "john.doe10@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe12", EmailAddress = "john.doe12@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe13", EmailAddress = "john.doe13@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe14", EmailAddress = "john.doe14@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe15", EmailAddress = "john.doe15@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe16", EmailAddress = "john.doe16@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe17", EmailAddress = "john.doe17@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe18", EmailAddress = "john.doe18@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe19", EmailAddress = "john.doe19@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe20", EmailAddress = "john.doe20@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe21", EmailAddress = "john.doe21@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe22", EmailAddress = "john.doe22@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe23", EmailAddress = "john.doe23@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe24", EmailAddress = "john.doe24@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe25", EmailAddress = "john.doe25@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe26", EmailAddress = "john.doe26@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe27", EmailAddress = "john.doe27@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe28", EmailAddress = "john.doe28@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe29", EmailAddress = "john.doe29@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe30", EmailAddress = "john.doe30@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe31", EmailAddress = "john.doe31@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe32", EmailAddress = "john.doe32@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe33", EmailAddress = "john.doe33@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe34", EmailAddress = "john.doe34@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe35", EmailAddress = "john.doe35@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe36", EmailAddress = "john.doe36@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe37", EmailAddress = "john.doe37@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe38", EmailAddress = "john.doe38@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe39", EmailAddress = "john.doe39@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe40", EmailAddress = "john.doe40@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) },
                    new User { Created = DateTime.Now.AddHours(-new Random().Next(1000)), Moniker = Guid.NewGuid(), Password = "NSBkCmpHo0xgOAxOeze18ReOoy6jC9IUjH7tgGtDhus=", Salt = "1n1YVgMRn9PGhLX3Lay7oGV13lQEnAXQOUcUeb1TiGc=", Role = Common.Enums.Role.StandardUser, RegistrationStatus = Common.Enums.RegistrationStatus.Full, FirstNames = "John", LastName = "Doe41", EmailAddress = "john.doe41@example.com", LastSignIn = DateTime.Now.AddHours(-new Random().Next(1000)) }

                );

                context.SaveChanges();

                string randomUserEmail = $"john.doe{new Random().Next(1, 40)}@example.com";
                var randomUser = context.Users.Single(c => c.EmailAddress == randomUserEmail);
                context.Products.Add(new Product() { User = randomUser, Created = DateTime.Now, Description = "John Doe's product", Name = "Product of John", Extension = ".png", Moniker = Guid.NewGuid(), ImageData = Convert.FromBase64String("iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAADmUlEQVR4AbxWPUxTURQ+99YYeVVxMTGQmLgZIkpABBNgdsAJCa0uBicSY9RR4mRwVOMAkwQHpUaZZHCHKC0/wWiMGxNqwtRoqwPt9Xzv9dTb19s+VEpzv95zz/edn3d73+vTtNPP8MeDTcl00ktkJhlvGV+9RHo7QIbtDHyT0BBrd5o2soH4SPoMF3nixfJZZdRzTjzGOM84RqRiAYhtgm8MGmgRg1iK+NRtIJ5IPzBKrROpUSKqq2XeHqxVo4hFDpsI2ywMu4jiV1bavcTyqiF1q5r9Ow9yeInMKnK6IqsaOJBc6jOF4gKR6XQF/KOvEzkPJFf6wvEVDaBLbfQ8i5oZuz2atSnOx5NLp+3EFQ1wlzNMNqI4p/VHsyH9lIYNH15//edgxfnAsWs3t53TOYahDi+28kgYfwdwu+CwiLPxs7neNLLUizp+A0bRDSwagf62QySw82ulb2Ktg6eWuorFnaEWAmCHgSTgMIc5rOG3+Td3T1JutpswC7CGFjBEI15isUU37ctdZIdm0EDbYRq/1Op3jLWN8aFWn0MyFLM52DaPtWgmXm0ScOHeZ3+2myCzf1Dzo7MfAQBEmFEEsw1JCF89fuHTd0jKuD/3hQD4MYOQJngXBnDlHXDWg13cpbP5iblNl8TpU0q1o4ETNuvaBWyvaKJ4XKlow7PdqM8Zc5wbMEf9RelLEthiscEBkIrPtoWDLwzo5ULKOkVHuIGwlPzDAi+CANiAbK8kAAeAA4SHLcCdAeDcQItY2UX+vylwA2pLxDLLYUGQdA0OwZglQS0emjDkTpDYgFdb3ABtBAv3N7oGI8Vh24jicTECR44NNMAvHHbKwI4nlwOj9B3e3ii+FBY1rWujDP/3R+mIHN1XBEXxFeLSArX1z+34a14XGVUDVwng96si2QEOcPG1/Bwmo4jaml6e+sGnEe8BQlTN+A2rnJajFl/LH4SaGdTGGSBl6HHg3Ltvqek3kHvR816RebhX5VELNVHPbwBGLtVzm0itUeM/a0GtoFC5ASxVTOG9IAu7QciqmEaNcnpdttjIPTv7oaiKg2w2ookscqMG5y+Pigbg/TXbu8hd4h1hF38OtYacyI0aNqoaAIku86lzXTgsWP8PkCOf6u5CTlceZwMixGFRxvALi5lmn/NhxX7XYK2ZRixyuATiq9sARLhd8qmea/mC18yPzsvsm2K8Y3zjB1ghALFN8E1BAy1iEMu6uuM3AAAA//+B/rYhAAAABklEQVQDAFcThZ6vm5MRAAAAAElFTkSuQmCC") });

                context.SaveChanges();
            }


        }
    }
}
